#!/usr/bin/bash

# qemu manual: https://www.qemu.org/docs/master/system/qemu-manpage.html

# -S: Do not start cpu at startup 
# -s: Shorthand for -gdb tcp::1234
qemu-system-x86_64 \
-S -s \
-drive format=raw,file=build/thread-os-$ARCH \
-serial none \
-nographic &

gdb -x /workspaces/NJU_OS/script/emu.gdb